- hosts: grafana
  vars:
    rpm: https://grafanarel.s3.amazonaws.com/builds/grafana-4.0.2-1481203731.x86_64.rpm
  tasks:
    - name: Upgrade all packages
      yum: name=* state=latest

    - name: Install grafana
      yum: name="{{ rpm }}" state=present

    - name: Install plugins
      command: grafana-cli --pluginsDir /grafana-plugins plugins install {{ item }}
      with_items:
        - grafana-piechart-panel
        - alexanderzobnin-zabbix-app
        - mtanda-histogram-panel

    - name: Copy config file
      copy: src="grafana.ini" dest=/etc/grafana owner=grafana

    - name: Make sure grafana user is the owner of its dirs
      file: name={{ item }} state=directory owner=grafana recurse=true
      with_items:
        - /grafana-plugins
        - /var/lib/grafana
        - /var/log/grafana

    - name: copy internal Red Hat legacy root certificate
      get_url:
        url: https://password.corp.redhat.com/cacert.crt
        dest: /etc/pki/ca-trust/source/anchors/redhat-legacy.crt
        mode: 0440
        validate_certs: no

    - name: Install openssl
      yum: name="openssl" state=present

    - name: prepare legacy root certificate
      command: openssl x509 -in redhat-legacy.crt -out redhat-legacy.pem -outform PEM
      args:
        chdir: /etc/pki/ca-trust/source/anchors

    - name: copy internal Red Hat IT certificate
      get_url:
        url: https://password.corp.redhat.com/RH-IT-Root-CA.crt
        dest: /etc/pki/ca-trust/source/anchors/redhat-root.crt
        mode: 0440
        validate_certs: no

    - name: prepare root certificate
      command: openssl x509 -in redhat-root.crt -out redhat-root.pem -outform PEM
      args:
        chdir: /etc/pki/ca-trust/source/anchors

    - name: update CA trust
      command: update-ca-trust extract
      args:
        chdir: /etc/pki/ca-trust/source/anchors

    - name: Clean yum files
      command: yum clean all
